version: '3.8'

services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ORG=mrnamcoin
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - coinswarmnet
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 512M
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
    ports:
      - "9090:9090"
    networks:
      - coinswarmnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - coinswarmnet
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    ports:
      - published: 9100
        target: 9100
        protocol: tcp
        mode: host
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    networks:
      - coinswarmnet
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    deploy:
      mode: global
      resources:
        limits:
          memory: 256M
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    networks:
      - coinswarmnet
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    deploy:
      replicas: 1
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - prometheus
      - influxdb
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    networks:
      - coinswarmnet
    restart: unless-stopped

volumes:
  influxdb_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  coinswarmnet:
    external: true