global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 60s
    static_configs:
      - targets: ['cadvisor:8080']

# remote_write:
#   - url: "http://influxdb:8086/api/v2/write?org=mrnamcoin&bucket=metrics&precision=s"
#     bearer_token: "4t8iGnq-ciT4AoFwduf2X5TT991EjzfyzHR2sH0zKWgUaPm0XcSjo6ykQMOQd2V3tmhJjzXisR2q2bSNTMykjw=="
#     queue_config:
#       max_samples_per_send: 10000
#       capacity: 20000